// Text cards without ffmpeg's drawtext (this build has no libfreetype): a text
// PNG generated by `imagine text` becomes a card scene, or an overlay asset —
// and because such a PNG carries alpha, a card scene composites onto the film's
// `output.background` instead of flattening to black.

import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { film, media, pixelAt, probe, project, type Project } from "./helpers.ts";

let p: Project;
let stubDir: string;
let prevPath: string;

/** A stub `imagine` whose `text render` writes the alpha fixture, like a resvg-enabled build. */
function stubImagine(): void {
  stubDir = mkdtempSync(join(tmpdir(), "filmkit-stub-text-"));
  writeFileSync(
    join(stubDir, "imagine"),
    `#!/bin/sh
{ echo "ARGV=$*"; } >> "$STUB_LOG"
case "$1" in
  models) echo '[{"name":"m","ready":true}]'; exit 0 ;;
  version) echo "imagine 0.2.0"; exit 0 ;;
esac
out=""
for a in "$@"; do case "$a" in --output=*) out="\${a#--output=}" ;; esac; done
[ -n "$out" ] || { echo "missing required option: --output" >&2; exit 2; }
case "$*" in
  *NO_RESVG*)
    echo "text render requires SVG rendering support; rebuild with 'zig build -Dsvg-overlay=true' and ensure libresvg is installed" >&2
    exit 1 ;;
esac
cp "$STUB_IMAGE" "$out"
`,
    { mode: 0o755 },
  );
  prevPath = process.env.PATH!;
  process.env.PATH = `${stubDir}:${prevPath}`;
}

/** A card scene plus a text overlay wired to a generated asset. */
function textFilm(overlayAsset: string, cardParams = "text: \"深夜律所走廊\""): string {
  return film({
    assets: overlayAsset,
    scenes: `  - id: s1
    duration: 2
    durationPolicy: exact
    impl: { profile: filmkit/static, task: clip }
    produces: { video: ./clip.mp4 }
  - id: card
    duration: 2
    durationPolicy: exact
    transition: { type: crossfade, duration: 0.4 }
    impl:
      profile: imagine
      task: text
      params: { ${cardParams}, width: 320, font: PingFang SC, size: 40, align: center }
    produces: { image: ./build/txt/card.png }`,
    tracks: `    - { id: lower, kind: overlay, asset: lower-third, position: bottom-left, margin: 12, width: 200, opacity: 0.9, from: 0.2, to: 3.5 }`,
    output: `  container: mp4
  video: { width: 320, height: 180, fps: 25, codec: h264 }
  audio: { codec: aac, sampleRate: 44100, channels: 2 }
  background: "0x0b1729"`,
  }).replace("  - ref: filmkit/ffmpeg", "  - ref: filmkit/ffmpeg\n  - ref: ./profiles/imagine.yaml");
}

const generatedOverlay = `  lower-third:
    kind: image
    impl:
      profile: imagine
      task: text
      params: { text: "源头，是内鬼", width: 320, font: PingFang SC, size: 28, align: left }
    produces: { image: ./build/txt/lower-third.png }`;

const close = (a: number, b: number, tolerance = 12) => Math.abs(a - b) <= tolerance;

beforeEach(() => {
  p = project();
  p.write("profiles/imagine.yaml", readFileSync(join(import.meta.dir, "../profiles/imagine.yaml"), "utf8"));
  media.mp4(p.path("clip.mp4"), 2, { w: 320, h: 180, audio: true });
  media.pngAlpha(p.path("card-alpha.png"), 64, 36, { w: 16, h: 8 });
  process.env.STUB_LOG = p.path("stub.log");
  process.env.STUB_IMAGE = p.path("card-alpha.png");
  writeFileSync(p.path("stub.log"), "");
  stubImagine();
});

afterEach(() => {
  process.env.PATH = prevPath;
  for (const k of ["STUB_LOG", "STUB_IMAGE"]) delete process.env[k];
  rmSync(stubDir, { recursive: true, force: true });
  p.cleanup();
});

describe("text cards from imagine text", () => {
  test("a transparent text PNG becomes a card scene on the film's background", () => {
    p.write("filmkit.yaml", textFilm(generatedOverlay));
    expect(p.cli("validate").exitCode).toBe(0);

    const plan = p.json<{ nodes: { id: string; executor: string }[] }>("plan");
    expect(plan.out!.nodes.map((n) => [n.id, n.executor])).toEqual([
      ["lower-third", "filmkit run"],
      ["card", "filmkit run"],
    ]);

    expect(p.cli("run", "lower-third").exitCode).toBe(0);
    expect(p.cli("run", "card").exitCode).toBe(0);
    // The rendered PNG carries alpha…
    expect(probe(p.path("build/txt/card.png")).format).toContain("png");
    expect(p.json<{ nodes: unknown[] }>("plan").out!.nodes).toHaveLength(0);

    const built = p.json<{ total: number }>("build");
    expect(built.exitCode).toBe(0);
    expect(built.out!.total).toBe(3.6); // 2 + 2 - 0.4

    // …so the card sits on `output.background` (0x0b1729 = 11,23,41), not on black,
    // and the opaque patch in the middle is still white.
    const [r, g, b] = pixelAt(p.path("build/t.mp4"), 3, 3, 3);
    expect(close(r!, 11) && close(g!, 23) && close(b!, 41)).toBe(true);
    const [cr, cg, cb] = pixelAt(p.path("build/t.mp4"), 160, 90, 3);
    expect(close(cr!, 255, 20) && close(cg!, 255, 20) && close(cb!, 255, 20)).toBe(true);

    // The card scene used the background-compositing path; the video scene kept pad+scale.
    const fg = readFileSync(p.path("build/compose.filtergraph.txt"), "utf8");
    expect(fg).toContain("color=c=0x0b1729:s=320x180:r=25");
    expect(fg).toContain("[bgc][fg]overlay=(W-w)/2:(H-h)/2");
    expect(fg).toMatch(/pad=320:180/);
  });

  test("the overlay window and placement reach the filtergraph", () => {
    p.write("filmkit.yaml", textFilm(generatedOverlay));
    p.cli("run", "lower-third");
    p.cli("run", "card");
    expect(p.cli("build").exitCode).toBe(0);
    const fg = readFileSync(p.path("build/compose.filtergraph.txt"), "utf8");
    expect(fg).toMatch(/overlay=12:main_h-overlay_h-12:shortest=1:enable='between\(t\\,0\.2\\,3\.5\)'/);
    expect(fg).toContain("scale=200:-1");
    expect(fg).toContain("colorchannelmixer=aa=0.9");
  });

  test("an opaque scene image keeps the plain scale+pad path", () => {
    media.png(p.path("card-opaque.png"), 64, 36, "0xff0000");
    p.write(
      "filmkit.yaml",
      film({
        scenes: `  - id: card
    duration: 2
    durationPolicy: exact
    impl: { profile: filmkit/static, task: clip }
    produces: { image: ./card-opaque.png }`,
        output: `  container: mp4
  video: { width: 320, height: 180, fps: 25, codec: h264 }
  audio: { codec: aac, sampleRate: 44100, channels: 2 }
  background: "0x0b1729"`,
      }),
    );
    expect(p.cli("build").exitCode).toBe(0);
    const fg = readFileSync(p.path("build/compose.filtergraph.txt"), "utf8");
    expect(fg).not.toContain("[bgc][fg]overlay");
    expect(fg).toMatch(/pad=320:180/);
    // An opaque image covers the frame: the background colour is behind the scaled picture only.
    const [r, g, b] = pixelAt(p.path("build/t.mp4"), 160, 90, 1);
    expect(close(r!, 255) && close(g!, 0) && close(b!, 0)).toBe(true);
  });

  test("a build without resvg support fails as a tool failure with the tool's own advice", () => {
    p.write("filmkit.yaml", textFilm(generatedOverlay, 'text: "NO_RESVG"'));
    const r = p.json("run", "card");
    expect(r.exitCode).toBe(4);
    expect(r.err!.errors[0]!.code).toBe("tool-failure");
    expect(r.err!.errors[0]!.hint).toMatch(/rebuild with 'zig build -Dsvg-overlay=true'/);
    expect(existsSync(p.path("build/txt/card.png"))).toBe(false);
  });

  test("the run records the imagine arguments verbatim (tool vocabulary)", () => {
    p.write("filmkit.yaml", textFilm(generatedOverlay));
    const run = p.json<{ argv: string[] }>("run", "card");
    expect(run.exitCode).toBe(0);
    const argv = run.out!.argv.join(" ");
    expect(argv).toContain("text render");
    expect(argv).toContain("--text=深夜律所走廊");
    expect(argv).toContain("--output=./build/txt/card.png"); // no cwd declared: stays film-relative
    expect(argv).toContain("--font=PingFang SC");
    expect(argv).toContain("--align=center");
    expect(argv).not.toContain("--stroke"); // unset optional flags are dropped
  });
});
