// `filmkit import script <notes.md>`: one-way conversion of a knowledge-script
// markdown file into a filmkit Film. Each `##` section becomes a scene whose
// narration is the section's text and whose picture is the section's first
// image (or a placeholder the agent fills in). Like `import hyperstory`, the
// importer never invents tool parameters: durations are documented estimates
// (durationPolicy: min lets the real TTS decide the floor), missing pictures
// show up in `plan` as work, and the result must pass `plan` immediately.
//
// Input shape (spec §9):
//   # Title            -> metadata.title (first H1 only)
//   ## Scene heading   -> one scene (id slugged from the heading)
//   paragraph text     -> intent.description (heading) + intent.narration.text
//   ![](path)          -> produces.image (first image of the section)

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, extname, resolve } from "node:path";
import { FilmkitError, io, invalid } from "./errors.ts";
import { loadFilm } from "./film.ts";
import { slug, yamlStr, type ImportResult } from "./import.ts";

/** Characters of narration per second for the duration estimate (spec §9). */
export const SCRIPT_CHARS_PER_SECOND = 4;
/** Floor for an estimated scene, seconds. */
export const SCRIPT_MIN_DURATION = 2;

interface ScriptScene {
  heading: string;
  narration: string;
  image?: string;
}

export function importScript(scriptPath: string, outPath: string, opts: { force?: boolean } = {}): ImportResult {
  if (!existsSync(scriptPath)) throw new FilmkitError(io(`file not found: ${scriptPath}`));
  if (existsSync(outPath) && !opts.force) {
    throw new FilmkitError(
      io(`refusing to overwrite ${outPath}`, { hint: "pass --force if you really want to replace it (the existing film is not read first)" }),
    );
  }
  let text: string;
  try {
    text = readFileSync(scriptPath, "utf8");
  } catch (err) {
    throw new FilmkitError(io(`cannot read ${scriptPath}: ${(err as Error).message}`));
  }
  const { title, scenes } = parseScript(text);
  if (scenes.length === 0) {
    throw new FilmkitError(invalid(`${scriptPath}: no scenes found; write one \`##\` section per scene`, { field: "scenes" }));
  }

  const warnings: string[] = [
    `durations are estimates (${SCRIPT_CHARS_PER_SECOND} narration characters per second, floor ${SCRIPT_MIN_DURATION}s); durationPolicy: min lets the produced narration decide the real length`,
  ];
  const annotations: Record<string, unknown> = { "script.source": basename(scriptPath) };
  const missingFiles: string[] = [];
  const usedIds = new Set<string>();
  const bodies: string[] = [];
  scenes.forEach((s, i) => {
    // A heading with no latin letters slugs to "item"; fall back to scene-NN so
    // ids stay readable (uniqueness is enforced either way).
    const numbered = `scene-${String(i + 1).padStart(2, "0")}`;
    const slugged = slug(s.heading);
    const base = slugged === "item" ? numbered : slugged;
    let id = base;
    for (let n = 2; usedIds.has(id); n++) id = `${base}-${n}`;
    usedIds.add(id);
    const image = s.image ?? `./assets/${id}.png`;
    if (!s.image) {
      warnings.push(`scenes[${i}] (${id}) has no image; produces.image points at ${image} for the agent to fill in`);
    }
    const duration = estimateDuration(s.narration);
    const body = [
      `  - id: ${id}`,
      `    duration: ${duration}`,
      `    durationPolicy: ${s.narration ? "min" : "exact"}`,
      `    intent:`,
      `      description: ${yamlStr(s.heading)}`,
    ];
    if (s.narration) body.push(`      narration: { text: ${yamlStr(s.narration)} }`);
    body.push(`    impl: { profile: filmkit/static, task: clip }`, `    produces: { image: ${yamlStr(image)} }`);
    bodies.push(body.join("\n"));
  });

  const name = slug(basename(scriptPath, extname(scriptPath)));
  const source = basename(scriptPath);
  const yaml =
    `# Generated by \`filmkit import script ${scriptPath}\`. Edit freely: filmkit never
# reads the script again, and never writes this file back to it.
apiVersion: filmkit/v1alpha1
kind: Film
metadata:
  name: ${name}
  title: ${yamlStr(title ?? name)}
  annotations:
    "script.source": ${yamlStr(source)}
profiles:
  - ref: filmkit/static
  - ref: filmkit/ffmpeg
assets: {}
output:
  container: mp4
  video: { width: 1920, height: 1080, fps: 30, codec: h264 }
  audio: { codec: aac, sampleRate: 48000, channels: 2 }
scenes:
${bodies.join("\n")}
`;

  try {
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, yaml, "utf8");
  } catch (err) {
    throw new FilmkitError(io(`cannot write ${outPath}: ${(err as Error).message}`));
  }
  // Prove the result is a legal film (schema + structure) before reporting success.
  const loaded = loadFilm(outPath);
  // Pictures the markdown names that are not on disk yet are the agent's first
  // work items (unlike hyperstory's asset uris, produces are checked for real).
  const filmDir = dirname(resolve(outPath));
  for (const s of loaded.film.scenes) {
    const image = s.produces.image;
    if (image && !existsSync(resolve(filmDir, image)) && !missingFiles.includes(image)) missingFiles.push(image);
  }
  return { out: outPath, scenes: bodies.length, assets: 0, annotations, warnings, missingFiles };
}

/** Estimate a scene's seconds from its narration text (spec §9): characters /
 *  SCRIPT_CHARS_PER_SECOND, rounded up to 0.1s, floored at SCRIPT_MIN_DURATION. */
export function estimateDuration(narration: string): number {
  if (!narration) return SCRIPT_MIN_DURATION;
  const chars = [...narration].length;
  return Math.max(SCRIPT_MIN_DURATION, Math.ceil((chars / SCRIPT_CHARS_PER_SECOND) * 10) / 10);
}

function parseScript(text: string): { title?: string; scenes: ScriptScene[] } {
  const lines = text.replace(/^\uFEFF/, "").replace(/\r\n?/g, "\n").split("\n");
  let title: string | undefined;
  const scenes: ScriptScene[] = [];
  let current: { heading: string; text: string[]; image?: string } | undefined;
  const flush = () => {
    if (!current) return;
    scenes.push({ heading: current.heading, narration: current.text.join(" ").trim(), image: current.image });
    current = undefined;
  };
  lines.forEach((raw) => {
    const line = raw.trim();
    if (line.startsWith("## ") || line === "##") {
      flush();
      const heading = line.replace(/^##\s*/, "").trim() || `Scene ${scenes.length + 1}`;
      current = { heading, text: [] };
      return;
    }
    // An H1 is the film title once; any later H1 outside a scene is ignored.
    if (line.startsWith("# ") || line === "#") {
      if (title === undefined && !current && scenes.length === 0) title = line.replace(/^#\s*/, "").trim() || undefined;
      else if (current) current.text.push(line);
      return;
    }
    if (!current) return; // prose before the first ## section is ignored (title area)
    const img = /!\[[^\]]*\]\(([^)]+)\)/.exec(line);
    if (img && current.image === undefined) {
      const uri = img[1]!.trim();
      // Remote images stay the author's problem: only local files become produces.
      if (uri && !/^[a-z]+:\/\//i.test(uri)) current.image = uri;
      return;
    }
    if (line === "" || line.startsWith("![")) return;
    current.text.push(stripMarkers(line));
  });
  flush();
  return { title, scenes };
}

/** Drop one leading list/quote marker (`-`, `*`, `>`, `1.`) so narration text is
 *  plain speech. Only the outermost marker is stripped, deterministically. */
function stripMarkers(line: string): string {
  return line.replace(/^(?:>\s*|[-*]\s+|\d+[.)]\s+)/, "").trim();
}
